### ISSUE TITLE
Convert Practicalli Spacemacs book to MkDocs

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/spacemacs#323]

**Comment by erichonorez** [comment]
Hi,

While reading the online book I noticed some typo and other small issues like broken links. I started to fix some of them here : https://github.com/practicalli/spacemacs/compare/main...erichonorez:spacemacs:main

Do I group all the fix in 1 PR ? Should I create a new issue or do I link the PR to this issue ?
How do you want to proceed ?

**Comment by practicalli-john** [comment]
The contributing page has been updated to clarify how to contribute, although I thought it was fairly clear.  Please let me know if its still unclear.

I've change the content in the areas mentioned. Thank you
